### ISSUE TITLE
Cannot launch Gazebo from Autoware in docker

### ISSUE THREAD

**Issue by tqshao** [huckl3b3rry87/Autoware#1]
I built and ran the Dockerfile.kinetic with nvidia docker2. Autoware launched successfully.

When I clicked the Gazebo button in Autoware Simulation, Gazebo didn't show up and I got the following errors:

`libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
[Err] [RenderEngine.cc:740] Unable to create glx visual
[Wrn] [RenderEngine.cc:93] Unable to create X window. Rendering will be disabled
[Wrn] [RenderEngine.cc:293] Cannot initialize render engine since render path type is NONE. Ignore this warning ifrendering has been turned off on purpose.
[ INFO] [1519340840.279750605]: Finished loading Gazebo ROS API Plugin.
[Msg] Waiting for master.
[ INFO] [1519340840.280590698]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 192.168.0.100
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
[Wrn] [ColladaLoader.cc:1804] Triangle input semantic: 'TEXCOORD' is currently not supported
[Wrn] [ColladaLoader.cc:1804] Triangle input semantic: 'TEXCOORD' is currently not supported
[Wrn] [ColladaLoader.cc:1804] Triangle input semantic: 'TEXCOORD' is currently not supported
[ERROR] [1519340841.071660689]: Couldn't open joystick /dev/input/js0. Will retry every second.
[ERROR] [1519340841.280868212]: Couldn't open joystick /dev/input/js1. Will retry every second.
Segmentation fault (core dumped)
[Wrn] [ColladaLoader.cc:1804] Triangle input semantic: 'TEXCOORD' is currently not supported
[Wrn] [ColladaLoader.cc:1804] Triangle input semantic: 'TEXCOORD' is currently not supported
[gazebo_gui-2] process has died [pid 2210, exit code 139, cmd /opt/ros/kinetic/lib/gazebo_ros/gzclient __name:=gazebo_gui __log:=/home/autoware/.ros/log/1233b150-1825-11e8-a62a-b06ebf2c81c1/gazebo_gui-2.log].
log file: /home/autoware/.ros/log/1233b150-1825-11e8-a62a-b06ebf2c81c1/gazebo_gui-2*.log
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Could not initialize OpenGL for RasterGLSurface, reverting to RasterSurface.
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
================================================================================REQUIRED process [rviz-10] has died!
process has died [pid 2618, exit code -11, cmd /opt/ros/kinetic/lib/rviz/rviz -d /home/autoware/Autoware/ros/src/system/gazebo/car_demo/car_demo/rviz/demo.rviz __name:=rviz __log:=/home/autoware/.ros/log/1233b150-1825-11e8-a62a-b06ebf2c81c1/rviz-10.log].
log file: /home/autoware/.ros/log/1233b150-1825-11e8-a62a-b06ebf2c81c1/rviz-10*.log
Initiating shutdown!
Traceback (most recent call last):
File "/opt/ros/kinetic/lib/gazebo_ros/spawn_model", line 313, in <module>
sm.callSpawnService()
File "/opt/ros/kinetic/lib/gazebo_ros/spawn_model", line 271, in callSpawnService
initial_pose, self.reference_frame, self.gazebo_namespace)
File "/opt/ros/kinetic/lib/python2.7/dist-packages/gazebo_ros/gazebo_interface.py", line 32, in spawn_urdf_model_client
resp = spawn_urdf_model(model_name, model_xml, robot_namespace, initial_pose, reference_frame)
File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
return self.call(*args, **kwds)
File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 523, in call
raise rospy.exceptions.ROSInterruptException("node shutdown interrupted service call")
rospy.exceptions.ROSInterruptException: node shutdown interrupted service call
[gazebo-1] escalating to SIGTERM
process[gazebo-1]: started with pid [2203]
process[gazebo_gui-2]: started with pid [2210]
process[robot_state_publisher-3]: started with pid [2239]
process[fake_localization-4]: started with pid [2304]
process[very_inaccurate_odom-5]: started with pid [2402]
process[joystick_translator-6]: started with pid [2465]
process[joy_node0-7]: started with pid [2478]
process[joy_node1-8]: started with pid [2541]
process[spawn_urdf-9]: started with pid [2586]
process[rviz-10]: started with pid [2618]
[rviz-10] killing on exit
[spawn_urdf-9] killing on exit
[joy_node0-7] killing on exit
[joystick_translator-6] killing on exit
[joy_node1-8] killing on exit
[very_inaccurate_odom-5] killing on exit
[fake_localization-4] killing on exit
[robot_state_publisher-3] killing on exit
[gazebo-1] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
`

**Comment by huckl3b3rry87** [comment]
This is no longer an issue
