### ISSUE TITLE
trajectory_generator branch - dependency issue for MAVs package

### ISSUE THREAD

**Issue by sumjos** [huckl3b3rry87/Autoware#4]
trajectory_generator branch depends on Mavs.jl package which in turn has build dependency on NLOptControl.

## Build dependency error
When running:
julia> Pkg.clone("https://github.com/huckl3b3rry87/MAVs.jl") , we get following error
INFO: Computing changes...
ERROR: fixed packages introduce conflicting requirements for NLOptControl: 
         MAVs requires versions [0.1.5+,∞) [none of the available versions can satisfy this requirement]
       available versions are 0.1.2, 0.1.3, 0.1.4 and 0.1.5

**Comment by huckl3b3rry87** [comment]
When installing julia and a bunch of new packages make sure to run
```
Pkg.update()
```
